### ISSUE TITLE
v1.1.1: Exception when DataPreservingTransactionTestCaseMixin is used and test is marked with @skip

### ISSUE THREAD

**Issue by frankoid** [brightinteractive/django-test-extras#2]
The following results in an exception when django-test-extras 1.1.1 is used, but works when django-test-extras 1.1.0 is used:

```
(goway)francis@murr goway $ ./manage test goway.PinterestShareSeleniumTests
Creating test database for alias 'default'...
Got an error creating the test database: (1007, "Can't create database 'goway_test'; database exists")
Type 'yes' if you would like to try deleting the test database 'goway_test', or 'no' to cancel: yes
Destroying old test database 'default'...
Installed 2 object(s) from 1 fixture(s)
Installed 22 object(s) from 1 fixture(s)
s
Traceback (most recent call last):
  File "/Users/francis/Code/Bright/python/goway/project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/core/management/commands/test.py", line 49, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/test_extras/management/commands/test.py", line 99, in handle
    self._core_handle(TestRunner, *test_labels, **options)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/test_extras/management/commands/test.py", line 158, in _core_handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/test/simple.py", line 382, in run_tests
    result = self.run_suite(suite)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/test_extras/testrunners.py", line 58, in run_suite
    verbosity=self.verbosity, failfast=self.failfast).run(suite)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/utils/unittest/runner.py", line 162, in run
    test(result)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/utils/unittest/suite.py", line 64, in __call__
    return self.run(*args, **kwds)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/utils/unittest/suite.py", line 84, in run
    self._wrapped_run(result)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/utils/unittest/suite.py", line 116, in _wrapped_run
    test(result)
  File "/Users/francis/env/goway/lib/python2.6/site-packages/test_extras/testcases.py", line 85, in __call__
    for (db, dumpfilepath) in self.database_dumpfilepaths.iteritems():
AttributeError: 'PinterestShareSeleniumTests' object has no attribute 'database_dumpfilepaths'
(goway)francis@murr goway $ 
```

PinterestShareSeleniumTests mixes in DataPreservingTransactionTestCaseMixin, and the only test method in it is marked with `@skip`.

**Comment by frankoid** [comment]
Moving `self.database_dumpfilepaths = {}` from `DataPreservingTransactionTestCaseMixin.setUp()` to `DataPreservingTransactionTestCaseMixin.__init__()` would probably make this error go away, it would be good to have a bit of a think about whether this is the right thing to do, in particular:
- does `__init__` get called for every test method? If not then things will get left in `self.database_dumpfilepaths` between tests, which will cause the wrong data to be restored.
- why doesn't `setUp` get called for `@skip`ped tests? I.e. have a look at the Django and/or unittest code and see how it handles `@skip`.
